spring:
  datasource:
    url: jdbc:h2:tcp://localhost/./mycommunity
    username: park
    password: 1234
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        # show_sql: true
        format_sql: true

# build.gradle 의 p6spy 로 대체하였다.
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6